### ISSUE TITLE
module 'cupy' has no attribute 'byte'[BUG]

### ISSUE THREAD

**Issue by gangadharsingh056** [rapidsai/cucim#102]
**Describe the bug**
While importing 
"from cucim.skimage.transform import resize", I am getting error as 
"AttributeError: module 'cupy' has no attribute 'byte'"

**Steps/Code to reproduce bug**
I am running the RAPIDS container: nvcr.io/nvidia/rapidsai/rapidsai:21.08-cuda11.2-runtime-ubuntu20.04
I have my:
cucim: 21.8.1 version
cupy: 9.0.0 version
CUDA Version: 11.4

**Expected behavior**
I want to test out the difference between skimage and cucim from this website: 
https://www.youtube.com/watch?v=G46kOOM9xbQ

**Environment details (please complete the following information):**
 - Environment location: Docker(20.10.8 version)
 - Method of cuCIM install: Docker RAPIDS 21.08 container
   - docker pull nvcr.io/nvidia/rapidsai/rapidsai:21.08-cuda11.2-runtime-ubuntu20.04
 

**Additional context**
Just need to resolve this error.

**Comment by grlee77** [comment]
This sounds like something may be wrong with the CuPy installation in that container. `cupy.byte` [is present in CuPy 9.0.0](https://github.com/cupy/cupy/blob/8de4cf8b0dc19199366c3ed839f3ee96f6d182ae/cupy/__init__.py#L120), so I am not sure why there would be an issue importing it.

Are you able to run a simple CuPy-only script such as:
```Python
import cupy
x = cupy.ones((32, 32))
```

**Comment by grlee77** [comment]
I could not reproduce on my Ubuntu 20.04 system. The `cucim.skimage.transform.resize` functions imported and ran okay in an interactive session using:

```
docker pull nvcr.io/nvidia/rapidsai/rapidsai:21.08-cuda11.2-runtime-ubuntu20.04
docker run --runtime=nvidia -it nvcr.io/nvidia/rapidsai/rapidsai:21.08-cuda11.2-runtime-ubuntu20.04
```
In the container, I started python and ran
```Python
import cupy
from cucim.skimage import transform
transform.resize(cupy.ones((4, 4)), (16, 16))
```
and the output was a shape (16, 16) array of ones as expected

**Comment by gangadharsingh056** [comment]
By re running the rapids container. It solved my problem.
And I checked all the code shared by you, they all are running fine now.

Thank you for your help.
