### ISSUE TITLE
[FEA] Multi-threading to load the entire image

### ISSUE THREAD

**Issue by drbeh** [rapidsai/cucim#139]
**Is your feature request related to a problem? Please describe.**
There are use cases in digital pathology that we want to load the entire image (WSI at a certain level) to the memory. Doing so with `cuCIM` seems to be much slower than other libraries, like `tifffile`, which uses multi-threading to load the entire image. Thus it would be very helpful is `cuCIM` can also support multi-threading and be able to perform on par with other libraries to load the entire image into memory.

Related issue: 
- https://github.com/Project-MONAI/MONAI/issues/3161
- https://github.com/Project-MONAI/MONAI/issues/3251

**Comment by gigony** [comment]
Loading the entire image is supported from cuCIM v21.12.01

https://github.com/rapidsai/cucim/wiki/release_notes_v21.12.01

**Comment by drbeh** [comment]
That is fantastic, @gigony! Thanks!
