### ISSUE TITLE
[QST] Citation?

### ISSUE THREAD

**Issue by rijobro** [rapidsai/cucim#187]
Hi, do you have a preferred way to cite this work? I've checked the README, readthedocss, old github issues, etc. and haven't seen it mentioned. Apologies if I've missed it somewhere.

Thanks in advance

**Comment by grlee77** [comment]
Hi @rijobro, thanks for checking

The best option at the moment is probably this Zenodo citation corresponding to our SciPy 2021 presentation: https://zenodo.org/record/5151998#.YcDYM7tOmGc

Given that much of `cucim.skimage` is based on code from scikit-image, you may also wish to cite scikit-image itself. Citation info for it is given on the front page of https://scikit-image.org. We hope to submit a newer scikit-image publication in 2022 (the original one is from 2014).

**Comment by rijobro** [comment]
Great, thanks for the info!

Might be worth adding to the README or somewhere else obvious?
