### ISSUE TITLE
[FEA] gpu enabled match_descriptors 

### ISSUE THREAD

**Issue by quasiben** [rapidsai/cucim#193]
I've heard from some folks that they would like to see an implementation of [match_descriptors](https://scikit-image.org/docs/dev/api/skimage.feature.html?highlight=match_descriptor#skimage.feature.match_descriptors) in cuCIM.  This might be challenging as I don't think [cdist](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html) is implemented in CuPy yet.

xref: https://github.com/scikit-image/scikit-image/blob/main/skimage/feature/match.py#L5

**Comment by jakirkham** [comment]
> I don't think [cdist](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html) is implemented in CuPy yet.

Filed issue ( https://github.com/cupy/cupy/issues/6307 )

**Comment by jakirkham** [comment]
cc @grlee77 @gigony (as we discussed this today)

**Comment by jakirkham** [comment]
PR ( https://github.com/cupy/cupy/pull/6690 ) is adding `cdist`

**Comment by jakirkham** [comment]
Moved to 22.10

There's not a project board for this yet. So moved to feature planning for now. Can update that later
