### ISSUE TITLE
[DOC] Add link to docs page in README

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/cucim#194]
Would be helpful for people getting started to have a link to the docs from the README

**Comment by jakirkham** [comment]
cc @jlefman @gigony @quasiben

**Comment by gigony** [comment]
Thanks @jakirkham for creating this issue!

Also would be useful to add some links for using CuPy, such as:

* Some examples of how to do asynchronous transfers ([async memcpy](https://docs.cupy.dev/en/stable/reference/generated/cupy.cuda.texture.CUDAarray.html?highlight=copy_from#cupy.cuda.texture.CUDAarray.copy_from)).
* [Basics of CuPy — CuPy 10.0.0 documentation](https://docs.cupy.dev/en/stable/user_guide/basic.html#data-transfer-basics)
* [Performance Best Practices — CuPy 10.0.0 documentation](https://docs.cupy.dev/en/stable/user_guide/performance.html)
* [Memory Management — CuPy 10.0.0 documentation](https://docs.cupy.dev/en/stable/user_guide/memory.html)

**Comment by jakirkham** [comment]
Yeah we need to think a bit about what lives in the docs here vs. in CuPy. Not sure what the right answer is.

Perhaps a good next step would be a corresponding [issue raised with CuPy]( https://github.com/cupy/cupy/issues ) highlighting parts of the documentation or questions that came up when using CuPy that were not otherwise clear. Having this perspective (particularly from new users) is incredibly helpful.

The fact that `cupy.asarray` copies asynchronously is certainly one. While several of us were pretty sure this was the case, the exact text in the CuPy docs saying this was hard to find. Maybe this should live as a note under [`cupy.asarray`]( https://docs.cupy.dev/en/stable/reference/generated/cupy.asarray.html#cupy.asarray ). That said, offline we did find [this text in the docs]( https://docs.cupy.dev/en/stable/user_guide/basic.html#current-stream ), which helped clarify this particular point:

> In CuPy, all CUDA operations such as data transfer (see the [Data Transfer]( https://docs.cupy.dev/en/stable/user_guide/basic.html#data-transfer-basics ) section) and kernel launches are enqueued onto the current stream, and the queued tasks on the same stream will be executed in serial (but asynchronously with respect to the host).

Another idea that came up in discussion was having a notebook covering these things. We do have [this notebook]( https://github.com/rapidsai/cudf/blob/branch-22.02/docs/cudf/source/user_guide/10min-cudf-cupy.ipynb ). Perhaps we could add a comment there.

**Comment by jakirkham** [comment]
This was done in PR: https://github.com/rapidsai/cucim/pull/315
