### ISSUE TITLE
[BUG] Transforms on cucim.clara use a fixed probability for the images in a batch

### ISSUE THREAD

**Issue by gigony** [rapidsai/cucim#225]
**Describe the bug**
Transforms introduced by https://github.com/rapidsai/cucim/wiki/release_notes_v21.10.00#1-add-high-performance-transforms-for-digital-pathology-100 use a fixed probability for the images in a batch.

**Steps/Code to reproduce bug**

Use this tutorial.

https://github.com/Project-MONAI/tutorials/tree/master/pathology/tumor_detection

**Additional context**

Using fixed probability reduced the accuracy of the results.

**Comment by jakirkham** [comment]
With PR ( https://github.com/rapidsai/cucim/pull/231 ) in, are we good to close or is there more needed here?

cc @shekhardw (for vis)

**Comment by gigony** [comment]
I think it's good to close this. Closing.

The remaining issue can be followed up by 
- #259
