### ISSUE TITLE
[DOC] API docs for `cucim.CuImage` not rendering

### ISSUE THREAD

**Issue by charlesbluca** [rapidsai/cucim#237]
## Report incorrect documentation

**Location of incorrect documentation**
The auto-generated API docs for `cucim.CuImage`:

- https://docs.rapids.ai/api/cucim/nightly/api.html#module-cucim.CuImage

The corresponding code for this:

- https://github.com/rapidsai/cucim/blob/branch-22.04/docs/source/api.rst#cuimage

**Describe the problems or issues found in the documentation**
The API docs for this class are not rendering:

![image](https://user-images.githubusercontent.com/20627856/159337534-86e76165-8a45-42da-8df1-8019cc986032.png)

**Steps taken to verify documentation is incorrect**
Comparing this page to the last stable docs build, I can see that these API docs used to get rendered properly for 21.12:

- https://docs.rapids.ai/api/cucim/stable/api.html#module-cucim.CuImage

**Suggested fix for documentation**
A local build could potentially clear up the issue here - has `CuImage` been relocated or removed?

**Comment by grlee77** [comment]
Thanks for reporting this. In addition to the missing `cucim.clara` docs, it looks like we are also missing docs for the functions under `cucim.core.operations`.

**Comment by grlee77** [comment]
or maybe the ones under 'core.operations' are still to be considered experimental as these are not automatically loaded into the top-level cucim namespace. we can discuss in the next community call
