### ISSUE TITLE
Lack of documentation on `cucim.CuImage`

### ISSUE THREAD

**Issue by drbeh** [rapidsai/cucim#263]
## Report needed documentation

**Report needed documentation**
There is no documentation on the `CuImage` API:
https://docs.rapids.ai/api/cucim/nightly/api.html#cuimage-submodules

**Describe the documentation you'd like**
It would be great to document the details of all the arguments and also more information on the returned `CuImage` object. After hours of debugging, I realized that `CuImage` is iterable that came as a surprise to me!

**Comment by gigony** [comment]
Duplicate of #237.
Closing this.
