### ISSUE TITLE
[FEA] refactor separable convolution for improved performance

### ISSUE THREAD

**Issue by grlee77** [rapidsai/cucim#321]
Benchmarking vs. [VPI](https://docs.nvidia.com/vpi/) indicates that a several-fold improvement may be possible. I will try to work on an implementation making better use of shared memory. Ideally this would be an n-d version of the row and column filters implemented here: https://github.com/opencv/opencv_contrib/tree/4.x/modules/cudafilters/src/cuda

**Comment by jakirkham** [comment]
There may be some overlapping interest on the Dask side. In particular there is some planned work around shared memory ( https://github.com/orgs/dask/projects/3/views/1 ). Happy to discuss further if it's of interest

**Comment by grlee77** [comment]
By shared, I meant small memory allocations declared as `__shared__` within a CUDA kernel. The use case is still for running on a single GPU, not distributing across multiple GPUs and/or nodes.

I think that Dask issue is more about the latter?

**Comment by jakirkham** [comment]
Ah ok. Yeah that's right
