### ISSUE TITLE
[BUG] some thresholding functions require scikit-image>=0.19

### ISSUE THREAD

**Issue by grlee77** [rapidsai/cucim#363]
**Describe the bug**

Changes made in #276 break use of some thresholding functions if the user does not have scikit-image >= 0.19. We should either bump our minimum requirement to 0.19 or provide a fallback.

**Steps/Code to reproduce bug**
many test failures are seen for `cucim/skimage/filters/tests/test_thresholding.py`

**Expected behavior**
all tests should pass

**Environment details (please complete the following information):**
cuCIM branch 22.08

**Comment by jakirkham** [comment]
It looks like we didn't bump this dependency. Should we be doing this?

https://github.com/rapidsai/cucim/blob/e155e320ab4bbe1e37f7d35dbd3870ccd8beed64/conda/recipes/cucim/meta.yaml#L35

**Comment by grlee77** [comment]
The functions failing with 0.18 are;
- `threshold_multiotsu` (`hist` kwarg isn't present in 0.18.x)
- `threshold_minimum`  (`max_iter` was deprecated in 0.19 and we use the new `max_num_iter` which wasn't present in 0.18)
- `try_all_threshold` (fails due to the same `threshold_minimum` failure)

All will work if the user upgrades to >=0.19.

**Comment by grlee77** [comment]
[This commit](https://github.com/rapidsai/cucim/pull/276/commits/fc7369557546719a7a0adb3f2919db5d54e60f20) where we deferred some computations to scikit-image and removed duplicate code is what lead to the issue.
