### ISSUE TITLE
Revisit usage of `--freeze-installed` with `conda` test dependency install

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/cucim#382]
Would be good to revisit this usage of `--freeze-installed` with `conda` when installing our test dependencies. It is possible this indicates some conflict that may be occurring.

_Originally posted by @jakirkham in https://github.com/rapidsai/cucim/pull/349#discussion_r936969611_

**Comment by grlee77** [comment]
Closing this as outdated. The place this was used in `run` was removed in #433 (switched to `pip` to install `opencv-python-headless`)
