### ISSUE TITLE
Adding `extras_require`

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/cucim#402]
We have a TODO flagged here for `install_requires`. Also `cupy` and other dependencies are not currently listed. It would be worthwhile to update these particularly for package formats relying on this metadata to be correct

https://github.com/rapidsai/cucim/blob/9f2338ed5c633df7dca29e56f90564cdfcea9756/python/cucim/setup.py#L86-L90

**Comment by gigony** [comment]
TODO: Adding cupy as `extra_requires`.

**Comment by jakirkham** [comment]
Based on discussion in today's meeting, there are use cases that rely on parts of cuCIM where CuPy or other dependencies are not needed. Given this, we think the right approach is to add these to [`extras_require`]( https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies ) under some extra name.

**Comment by jakirkham** [comment]
This was resolved in PR: https://github.com/rapidsai/cucim/pull/617
