### ISSUE TITLE
[QST] Will there be a python 3.10 compatible release?

### ISSUE THREAD

**Issue by ekhahniii** [rapidsai/cucim#466]
Will there be a python 3.10 compatible release?

**Comment by jakirkham** [comment]
Not this release, but looking into next release. Relevant [notice]( https://docs.rapids.ai/notices/rsn0023/ )

**Comment by jakirkham** [comment]
FWIW PR ( https://github.com/rapidsai/cucim/pull/476 ) adds Python 3.10 to CI and [Conda packages to `rapidsai-nightly`]( https://anaconda.org/rapidsai-nightly/cucim/files ).

There will still be work needed for wheels.

**Comment by jakirkham** [comment]
Closing as this was completed some time ago
