### ISSUE TITLE
[FEA] add cucim.skimage.measure.find_contour

### ISSUE THREAD

**Issue by grlee77** [rapidsai/cucim#470]
**Is your feature request related to a problem? Please describe.**

`find_contour` is a missing function that [could be used by MONAI](https://github.com/Project-MONAI/MONAI/blob/c10cdd226d94f06600a929de13c5d78bda6e8a10/monai/apps/pathology/transforms/post/array.py#L33-L38) to accelerate existing postprocessing transforms

**Describe the solution you'd like**
Create a GPU-based implementation matching the behavior of `skimage.measure.find_contours`

**Describe alternatives you've considered**

**Additional context**

**Comment by jakirkham** [comment]
Think we opened these at the same time ( https://github.com/rapidsai/cucim/issues/469 ) 😂 

Happy to close

**Comment by grlee77** [comment]
no worries, let's just close this duplicate one!
