### ISSUE TITLE
Double `else` in `benchmark_zarr_write_lz4_via_dask.py`

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/cucim#484]
https://github.com/rapidsai/cucim/blob/8a660808c0a7b7513d3ce97cfd1743891877237c/examples/python/gds_whole_slide/benchmark_zarr_write_lz4_via_dask.py#L69-L75

This double `else` looks odd. What was intended?

Looking at the error message would have thought this

<details>

```suggestion
    if dtype == 'uint8':
        img = image_gpu
        assert img.dtype == cp.uint8
    elif dtype == 'uint16':
        img = image_gpu
        assert img.dtype == cp.uint16
    else:
        raise NotImplementedError("only testing for uint8 and uint16")
```

</details>

Though maybe the error is simply not needed? However then the `if` is probably unnecessary too

<details>

```suggestion
    img = image_gpu.astype(dtype)
```

</details>

_Originally posted by @jakirkham in https://github.com/rapidsai/cucim/pull/452#discussion_r1083065453_

cc @bdice @grlee77

**Comment by bdice** [comment]
@grlee77 Gentle poke on this, since it blocks #474. There's no time pressure on that PR, so whenever it's convenient please take a peek.
