### ISSUE TITLE
[FEA] Missing IntelliSense capability in VSCode

### ISSUE THREAD

**Issue by alexkrz** [rapidsai/cucim#489]
**Is your feature request related to a problem? Please describe.**
After installing cucim, unfortunately I cannot get IntelliSense features like auto-complete in Visual Studio Code. According to https://github.com/microsoft/pylance-release/issues/242 this is due to the fact that the Pylance extension does not support IntelliSense for compiled libraries.

**Describe the solution you'd like**
As described in https://github.com/microsoft/pylance-release/issues/242 it would be necessary to provide a type stub ("pyi") file for the library interface.
I would very much appreciate if such a type stub file could be provided.

**Describe alternatives you've considered**
Interestingly, IntelliSense features are working for me in PyCharm. Haven't figured out the reason why PyCharm can auto-generate the type stubs and VSCode can't..

**Comment by grlee77** [comment]
Thanks, @alexkrz. The use of `.pyi` files was introduced in recent months to scikit-image and should appear in the 0.20 release. 

Let me update to use .pyi files here as well (port changes from https://github.com/scikit-image/scikit-image/pull/6577). I will target this for the 2023.04.00 milestone.
