### ISSUE TITLE
cuCIM: Need to canonicalize dlopen'd names

### ISSUE THREAD

**Issue by leofang** [rapidsai/cucim#504]
Documenting an offline discussion with @jakirkham in preparation of CUDA 12 bring-up on conda-forge.

Currently, there're some places where `libXXXXX.so` without any SONAME being dlopen'd, for example,
https://github.com/rapidsai/cucim/blob/90d021eaf3cde68f73159db7b1b6b69d6cc27395/gds/src/cufile_stub.cpp#L64
There will become problematic because the `libXXXXX.so` symlink is supposed to exist only in the `libXXXXX-dev` package by the stand practice of Linux distros, not in `libXXXXX` which only contains `libXXXXX.so.{major}`. The dlopen'd names need to be canonicalized.

**Comment by vyasr** [comment]
Please assign this issue to me.

**Comment by jakirkham** [comment]
Done. Thanks Vyas! 🙏

**Comment by jakirkham** [comment]
Submitted PR ( https://github.com/rapidsai/cucim/pull/548 ) in an attempt to address this borrowing heavily from cuDF and KvikIO
