### ISSUE TITLE
[QST] conda compatibility with scikit-image 0.20.0

### ISSUE THREAD

**Issue by accelyte** [rapidsai/cucim#531]
scikit-image recently updated to 0.20.0 on conda-forge, however cucim's dependencies explicitly prevent 0.20.0 or above from being installed. Is there any reason why this limitation is in place, especially when cucim's API is already using the 0.20.0 scikit-image API?

**Comment by grlee77** [comment]
Hi @accelyte, thank you for reporting the issue! I will bump the conda version pinnings to allow scikit-image 0.20 as well.

I will update here once I know whether or not this will make it in for the 23.04 release later this week. 

As a workaround in the meantime, the PyPI version of the package does not have the version restriction. You could install it into a conda environment with `pip install cucim` after installing cupy and scikit-image via conda.

**Comment by jakirkham** [comment]
Also it should be possible to get [`cucim` 23.04 Conda dev packages from `rapidsai-nightly`]( https://anaconda.org/rapidsai-nightly/cucim/files?version=23.04.00a ), which have this constraint relaxed (as noted by the recent change)
