### ISSUE TITLE
[BUG] CUDA_ERROR_ILLEGAL_ADDRESS with `morphology.isotropic_closing`

### ISSUE THREAD

**Issue by accelyte** [rapidsai/cucim#539]
**Describe the bug**
I accidentally landed on a specific combination of conditions which causes illegal address access, resulting in a crash. I believe this has something to do with the time taken to write to memory, whilst another operation is happening. However, the timing required is incredibly inconsistent: sometimes it will happen repeatedly, then start working for a while, and go back to crashing.

**Steps/Code to reproduce bug**
Snippet 1 (MVP of my actual code):
```py
import cupy as cp
from cucim.skimage import morphology
x = cp.random.rand(1000, 1000)  # some large array simulating a 2D image
y = x.copy()
y = y >= 0.1
morphology.isotropic_closing(y, 3)
```
- all at once (in a function): crashes 5/5 times
- wait 10 seconds between `y = y >= 0.1` and `morphology.isotropic_closing(y, 3)`: crashes 5/5 times

Snippet 2:
```py
import cupy as cp
from cucim.skimage import morphology
x = cp.random.rand(1000, 1000)  # some large array simulating a 2D image
y = x.copy()
z = y >= 0.1
morphology.isotropic_closing(z, 3)
```
- doesn't crash

Snippet 3:
```py
import cupy as cp
from cucim.skimage import morphology
x = cp.random.rand(1000, 1000)  # some large array simulating a 2D image
y = x >= 0.1
morphology.isotropic_closing(y, 3)
```
- all at once (in a function): crashes 5/5 times
- wait 10 seconds between `y = x >= 0.1` and `morphology.isotropic_closing(y, 3)`: crashes 3/5 times

**Expected behavior**
All of the above snippets should run fine.

**Environment details (please complete the following information):**
 - Environment location: HPC Cluster
 - Method of cuCIM install: conda, stable v23.02 and nightly v23.04a
 - GPU: Tesla V100-SXM2-32GB
 - CUDA: 11.4

**Additional context**
- This ONLY happens to `morphology.isotropic_closing`, `morphology.isotropic_opening` works fine
- `morphology.binary_closing` (i.e. `morphology.binary_closing(y, morphology.disk(3))`) works fine
-  When digging through the GitHub issues, I also found https://github.com/rapidsai/cucim/pull/421#issuecomment-1330140735, not sure if relevant.

**Comment by grlee77** [comment]
Thanks for reporting the issue. I saw this type of failure inconsistently on CI earlier this week (albeit only for aarch64, not x86_64). I was unable to reproduce it running the test suite locally. I will try to look into it again and see where the issue could be occurring.

**Comment by grlee77** [comment]
I was unable to reproduce with size (1000, 1000) even if running many times, but it did fail when running with size (4000, 4000) for me. The traceback pointed to a specific kernel within the 2D parallel banding algorithm used for the distance transform:
```py
File ~/Dropbox/Quansight/public/NVIDIA/cucim/python/cucim/src/cucim/core/operations/morphology/_pba_2d.py:416, in _pba_2d(arr, sampling, return_distances, return_indices, block_params, check_warp_size, float64_distances, distances, indices)
    409 kernelPropagateInterband(
    410     grid,
    411     block,
    412     (input_arr, margin, size, bandSize1),
    413 )
    414 # kernelUpdateVertical stores output into an intermediate array of
    415 # transposed shape
--> 416 kernelUpdateVertical(
    417     grid,
    418     block,
    419     (input_arr, margin, output, size, bandSize1),
    420 )
    422 # phase 2
    423 block = (block_size, 1, 1)
File ~/src/public/cupy/cupy/_core/raw.pyx:89, in cupy._core.raw.RawKernel.__call__()

File ~/src/public/cupy/cupy/cuda/function.pyx:224, in cupy.cuda.function.Function.__call__()

File ~/src/public/cupy/cupy/cuda/function.pyx:206, in cupy.cuda.function._launch()

File ~/src/public/cupy/cupy_backends/cuda/api/driver.pyx:253, in cupy_backends.cuda.api.driver.launchKernel()

File ~/src/public/cupy/cupy_backends/cuda/api/driver.pyx:60, in cupy_backends.cuda.api.driver.check_status()

CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered

```

I would guess the difference in size at which it occurs relates to grid/block size settings and differences between GPU models. It seems perhaps the default setting of these parameters is not working as expected in some cases.
