### ISSUE TITLE
[FEA] Migrate `jpeg` to `libjpeg-turbo`

### ISSUE THREAD

**Issue by raydouglass** [rapidsai/cucim#544]
`cucim` should consider migrating the `jpeg` dependency in `libcucim` (https://github.com/rapidsai/cucim/blob/branch-23.06/conda/recipes/libcucim/meta.yaml#L50) to `libjpeg-turbo`.

The reason for this is that `conda-forge` is migrating these libraries: https://github.com/conda-forge/conda-forge.github.io/issues/673

Additionally, semi-related, this caused a problem in the `23.04` release which was resolved in #541.

**Comment by jakirkham** [comment]
cc @grlee77 @gigony

**Comment by gigony** [comment]
Closing this as libjpeg dependency is removed by https://github.com/rapidsai/cucim/pull/557

**Comment by jakirkham** [comment]
Thanks Gigon! 🙏
