### ISSUE TITLE
Intermittent test failure: `test_read_region_cpu_memleak[testimg_tiff_stripe_4096×4096_256_deflate]`

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/cucim#625]
> I am seeing an error message regarding cpu memory usage:
https://github.com/rapidsai/cucim/actions/runs/6698898284/job/18202421711?pr=620
![image](https://github.com/rapidsai/cucim/assets/1928522/a82463b3-1612-4126-b75a-04c72ed18671)
> 
> It is likely that it is intermittent issue (may need to increase the threshold > 1273671680 - 1223131136 = 50540544).

_Originally posted by @gigony in https://github.com/rapidsai/cucim/issues/620#issuecomment-1786179731_

**Comment by gigony** [comment]
Addressed by https://github.com/rapidsai/cucim/pull/623
Closing this.
