### ISSUE TITLE
Cannot install cucim by using conda or pip

### ISSUE THREAD

**Issue by cosecdelta** [rapidsai/cucim#637]
![Capture](https://github.com/rapidsai/cucim/assets/63477668/d390f8b6-ef99-4e90-96e4-573ccaea588f)

As described in the screenshot when trying to install the cucim package through conda-install or by using pip it is showing that the package is not available in the necessary channels.

**Comment by jakirkham** [comment]
Unfortunately Windows is not supported

WSL could be used though

More details in this comment: https://github.com/rapidsai/cucim/issues/454#issuecomment-1331244039

**Comment by gigony** [comment]
Closing this. Windows support-relased questions are discussed in https://github.com/rapidsai/cucim/issues/454#issuecomment-1331244039
