### ISSUE TITLE
[BUG] `click` is listed only in test requirements but is a required in order to use `cucim.clara`

### ISSUE THREAD

**Issue by grlee77** [rapidsai/cucim#703]
**Describe the bug**
`click` should not be required unless the CLI `convert` tool based on it is used.

**Steps/Code to reproduce bug**

@drbeh reported that `pip` installing the recent PyPI release of 24.02 and then trying
```py
from cucim import CuImage
```
results in 
```
ModuleNotFoundError: No module named 'click'
```

**Expected behavior**
It is possible to use `cucim.clara` classes other than the `convert` command-line utility if `click` is not installed.

**Environment details (please complete the following information):**

**Additional context**

**Comment by jakirkham** [comment]
Thanks Greg! 🙏

We should also consider adding a test that tries `import`s without the test dependencies installed. This could flag similar issues for us in the future

**Comment by jakirkham** [comment]
Currently this is just in test requirements

https://github.com/rapidsai/cucim/blob/eee3e4c3ae6521b532978f20e7083a5a3ea8287d/python/cucim/pyproject.toml#L57-L60
