### ISSUE TITLE
Replace or drop `pytest-lazy-fixture`

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/cucim#755]
After some recent unrelated testing work, we learned that `pytest-lazy-fixture` is incompatible with `pytest` version `8.0.0` or newer. This has been the case for 6 months now as this issue notes: https://github.com/TvoroG/pytest-lazy-fixture/issues/65

Given this we may want to drop or replace this dependency

One option on the replacement side is `pytest-lazy-fixtures`, which it looks straightforward to switch to

**Comment by jakirkham** [comment]
cc @grlee77

**Comment by grlee77** [comment]
It is not used for `cucim.skimage` or `cucim.core` test cases. but is used for some I/O related ones under `python/cucim/tests/`. It is imported [here](https://github.com/rapidsai/cucim/blob/branch-24.10/python/cucim/tests/fixtures/testimage.py) in a helper module loaded by the `python/cucim/tests/conftest.py`.

**Comment by gigony** [comment]
Thanks @jakirkham and @grlee77 !
Let me check if I can replace with `pytest-lazy-fixtures`.

**Comment by jakirkham** [comment]
This was done in PR: https://github.com/rapidsai/cucim/pull/756

Thanks Gigon! 🙏
