### ISSUE TITLE
Pip install failure on Linux

### ISSUE THREAD

**Issue by Elliot-QxZhang** [rapidsai/cucim#779]
Hi!

I just found that I cannot use Pip or conda to install cucim. My CUDA version is 11.8. I use the script pip install cucim-cu11, but I received

Collecting cucim-cu11
  Downloading cucim-cu11-23.12.1.tar.gz (6.8 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-kjyijayy/cucim-cu11_3faaf0ae7c944533982a22ed9b5060db/setup.py", line 137, in <module>
          raise RuntimeError(open("ERROR.txt", "r").read())
      RuntimeError:
      ###########################################################################################
      The package you are trying to install is only a placeholder project on PyPI.org repository.
      This package is hosted on NVIDIA Python Package Index.
      
      This package can be installed as:
      ```
      $ pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com cucim-cu11
      ```
      ###########################################################################################
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

I have tried to use pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com cucim-cu11, but I still receive the same results. I have also try to update my pip module and setuptools, but it didn't work.

Thanks

**Comment by gigony** [comment]
Hi @Elliot-QxZhang ,

Could you please let us know which OS and Python version you are using?

The current `cucim-cu11` [Python package](https://pypi.org/project/cucim-cu11/#files) supports Python 3.9/3.10/3.11 (no support for Python 3.8 or 3.12), and I suspect the current registry may not support your system.

Please check if you can install the older version of cucim (https://pypi.org/project/cucim/#files) that supports Python 3.8.

```
python3 -m pip install cucim
```

Also please try to upgrade pip and setuptools version

```sh
python3 -m pip install --upgrade setuptools pip
```

Thanks!

**Comment by Elliot-QxZhang** [comment]
Thank you for your reply. I have succeeded in installing it. It was the wrong Python version. Thanks anyway.
