### ISSUE TITLE
[FEA] Add Stain Normalization operation (in Python)

### ISSUE THREAD

**Issue by gigony** [rapidsai/cucim#96]
**Is your feature request related to a problem? Please describe.**

We need to add Stain Normalization algorithm to a part of cuCIM's operation:
   https://developer.nvidia.com/blog/accelerating-digital-pathology-pipelines-with-nvidia-clara-deploy

**Describe the solution you'd like**

Need to move the implementation to cuCIM's package: https://github.com/Project-MONAI/MONAI/pull/2666

@drbeh helped push a draft PR
- https://github.com/rapidsai/cucim/pull/186

We would like to update and merge it.

**Describe alternatives you've considered**
N/A

**Additional context**

We also have C++ implementation.
Once Operator interface is available, we can provide the operation with C++ implementation.

**Comment by drbeh** [comment]
Hi @gigony, is it going to be a CuPy implementation? If so, I can help with that.
